services:
  cli:
    build:
      context: .
      args:
        GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
    user: "1000:1000"
    hostname: capsule
    group_add:
      - "${DOCKER_GID:-999}"
    working_dir: /home/workspace
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_GID=${DOCKER_GID:-999}
    restart: "no"
    volumes:
      - ${CAPSULE_WORKDIR:-${CC_WORKDIR:-${PWD}}}:/home/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - home:/home/user
      - mise:/mise

volumes:
  home:
  mise:
