services:
  cli:
    build: .
    user: "8888:100"
    group_add:
      - "${DOCKER_GID:-999}"
    working_dir: /home/workspace
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_GID=${DOCKER_GID:-999}
    restart: "no"
    volumes:
      - ${CAPSULE_WORKDIR:-${CC_WORKDIR:-${PWD}}}:/home/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - home:/home/user

volumes:
  home:
